
import type { Campaign, SKUItem } from './types';

export const mockCampaigns: Campaign[] = [
  {
    id: 'CAM-X4K8',
    brandName: 'AquaFizz',
    programName: 'Summer Splash Sale',
    campaignType: 'Lazada Campaign',
    startDate: '2024-07-01',
    endDate: '2024-07-31',
    objectives: 'Increase sales by 20% and brand awareness.',
    status: 'Submitted',
    remarks: 'Awaiting ShopOps validation.',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-06-15',
    tradeLetterDate: '2024-06-15',
    distributor: 'Global Beverages Inc.',
    promotionDuration: '1 month',
    website: 'https://aquafizz.com/summer',
    extractedRemarks: 'Standard summer promotion terms apply.',
    promotions: [
      { productName: 'AquaFizz Original', barcode: '123456789012', srp: 1.50, discountedPrice: 1.20, discountValue: 0.30, discountPercentage: 20 },
      { productName: 'AquaFizz Lemon', barcode: '123456789013', srp: 1.50, discountedPrice: 1.20, discountValue: 0.30, discountPercentage: 20 },
    ],
    approvers: ['John Doe', 'Jane Smith'],
  },
  {
    id: 'CAM-L9P1',
    brandName: 'Scholar Backpacks',
    programName: 'Back to School Bonanza',
    campaignType: 'Shopee Campaign',
    startDate: '2024-08-15',
    endDate: '2024-09-15',
    objectives: 'Capture 15% of the back-to-school market share.',
    status: 'Submitted',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-07-20',
    tradeLetterDate: '2024-07-20',
    distributor: 'Stationery World',
    promotionDuration: '1 month',
    website: 'https://scholarbackpacks.com/bts',
    extractedRemarks: 'Early bird discount available for the first week.',
    promotions: [
      { productName: 'Classic Backpack', barcode: '234567890123', srp: 45.00, discountedPrice: 35.00, discountValue: 10.00, discountPercentage: 22.22 },
    ],
    approvers: ['Alice Johnson'],
  },
  {
    id: 'CAM-A2B7',
    brandName: 'VitaBoost',
    programName: 'Winter Wellness Program',
    campaignType: 'Vouchers',
    status: 'Draft',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-10-01',
    startDate: '2024-11-01',
    endDate: '2024-12-31',
    objectives: 'Promote healthy living during winter.',
    tradeLetterDate: '2024-10-10',
    distributor: 'HealthyYou Pharma',
    promotionDuration: '2 months',
    website: '',
    extractedRemarks: 'Bundle deals available with Vitamin C.',
    promotions: [
        { productName: 'VitaBoost D3', barcode: '345678901234', srp: 20.00, discountedPrice: 15.00, discountValue: 5.00, discountPercentage: 25 },
        { productName: 'VitaBoost Multivitamin', barcode: '345678901235', srp: 30.00, discountedPrice: 25.00, discountValue: 5.00, discountPercentage: 16.67 },
    ],
    approvers: ['Bob Williams'],
  },
  {
    id: 'CAM-QW3R',
    brandName: 'NextGen',
    programName: 'Tech Gadget Expo',
    campaignType: 'Lazada Campaign',
    status: 'Returned',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-09-01',
    startDate: '2024-10-10',
    endDate: '2024-10-20',
    objectives: 'Generate leads and pre-orders for the new smartwatch.',
    remarks: 'Budget is too high. Please revise and resubmit.',
    tradeLetterDate: '2024-09-01',
    distributor: 'TechForward Retail',
    promotionDuration: '10 days',
    website: 'https://nextgen.tech/expo',
    extractedRemarks: 'Exclusive color for expo attendees.',
    promotions: [
      { productName: 'NextGen Smartwatch Series 5', barcode: '456789012345', srp: 399.00, discountedPrice: 349.00, discountValue: 50.00, discountPercentage: 12.53 },
    ],
    approvers: ['Charles Brown', 'David Garcia'],
  },
  {
    id: 'CAM-Z1O5',
    brandName: 'Gourmet Turkeys',
    programName: 'Holiday Feast Deal',
    campaignType: 'Shopee Campaign',
    status: 'Active',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-11-10',
    startDate: '2024-12-01',
    endDate: '2024-12-25',
    objectives: 'Become the top choice for holiday meals.',
    tradeLetterDate: '2024-11-15',
    distributor: 'FarmFresh Foods',
    promotionDuration: '25 days',
    website: 'https://gourmetturkeys.com/holiday',
    extractedRemarks: 'Free recipe book with every purchase.',
    promotions: [
      { productName: '12lb Gourmet Turkey', barcode: '567890123456', srp: 50.00, discountedPrice: 40.00, discountValue: 10.00, discountPercentage: 20 },
    ],
    approvers: ['Emily White'],
  },
  {
    id: 'CAM-J6M9',
    brandName: 'EcoClean',
    programName: 'Spring Cleaning Essentials',
    campaignType: 'Lazada Campaign',
    status: 'Completed',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-03-01',
    startDate: '2024-04-01',
    endDate: '2024-04-30',
    objectives: 'Boost Q2 sales.',
    tradeLetterDate: '2024-03-10',
    distributor: 'CleanHome Supplies',
    promotionDuration: '1 month',
    website: 'https://ecoclean.com/spring',
    extractedRemarks: 'Buy one get one 50% off.',
    promotions: [
      { productName: 'All-Purpose Cleaner', barcode: '678901234567', srp: 5.00, discountedPrice: 5.00, discountValue: 0.00, discountPercentage: 0 },
      { productName: 'Glass Cleaner', barcode: '678901234568', srp: 4.00, discountedPrice: 2.00, discountValue: 2.00, discountPercentage: 50 },
    ],
    approvers: ['Frank Miller'],
  },
  {
    id: 'CAM-P0N3',
    brandName: 'FitTrack',
    programName: 'New Year Fitness Challenge',
    campaignType: 'Bundle Deals',
    status: 'Submitted',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-12-01',
    startDate: '2025-01-01',
    endDate: '2025-01-31',
    objectives: 'Promote fitness resolutions.',
    remarks: '',
    tradeLetterDate: '2024-12-05',
    distributor: 'Fitness Universe',
    promotionDuration: '31 days',
    website: 'https://fittrack.com/newyear',
    extractedRemarks: 'Join the challenge and win prizes.',
    promotions: [
      { productName: 'FitTrack Pro Band', barcode: '789012345678', srp: 120.00, discountedPrice: 99.00, discountValue: 21.00, discountPercentage: 17.5 },
    ],
    approvers: ['Grace Lee', 'Henry Wilson'],
  },
  {
    id: 'CAM-DUP1',
    brandName: 'AquaFizz',
    programName: 'Winter Splash Sale',
    campaignType: 'Lazada Campaign',
    status: 'Submitted',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-11-15',
    startDate: '2024-12-01',
    endDate: '2024-12-31',
    objectives: 'Increase sales by 10% in winter.',
    remarks: 'Awaiting validation for winter promo.',
    tradeLetterDate: '2024-11-15',
    distributor: 'Global Beverages Inc.',
    promotionDuration: '1 month',
    website: 'https://aquafizz.com/winter',
    extractedRemarks: 'Winter special.',
    promotions: [
      { productName: 'AquaFizz Original', barcode: '123456789012', srp: 1.50, discountedPrice: 1.30, discountValue: 0.20, discountPercentage: 13.33 },
    ],
    approvers: ['John Doe'],
  },
  {
    id: 'CAM-DUP2',
    brandName: 'Scholar Backpacks',
    programName: 'Summer Getaway Pack',
    campaignType: 'Shopee Campaign',
    status: 'Completed',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-05-20',
    startDate: '2024-06-01',
    endDate: '2024-06-30',
    objectives: 'Sell off summer stock.',
    tradeLetterDate: '2024-05-20',
    distributor: 'Stationery World',
    promotionDuration: '1 month',
    website: 'https://scholarbackpacks.com/summer-sale',
    extractedRemarks: 'Final sale items.',
    promotions: [
      { productName: 'Travel Backpack', barcode: '234567890124', srp: 65.00, discountedPrice: 40.00, discountValue: 25.00, discountPercentage: 38.46 },
    ],
    approvers: ['Alice Johnson'],
  },
  {
    id: 'CAM-DUP3',
    brandName: 'VitaBoost',
    programName: 'Spring Vitality Pack',
    campaignType: 'Vouchers',
    status: 'Draft',
    createdBy: 'commercial@demo.com',
    createdAt: '2025-02-01',
    startDate: '2025-03-01',
    endDate: '2025-03-31',
    objectives: 'Boost spring sales.',
    tradeLetterDate: '2025-02-10',
    distributor: 'HealthyYou Pharma',
    promotionDuration: '1 month',
    website: '',
    extractedRemarks: 'New formula launch.',
    promotions: [
        { productName: 'VitaBoost B12', barcode: '345678901236', srp: 22.00, discountedPrice: 18.00, discountValue: 4.00, discountPercentage: 18.18 },
    ],
    approvers: ['Bob Williams'],
  },
  {
    id: 'CAM-DUP4',
    brandName: 'EcoClean',
    programName: 'Autumn Refresh',
    campaignType: 'Tiktok Campaign',
    status: 'Active',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-08-15',
    startDate: '2024-09-01',
    endDate: '2024-09-30',
    objectives: 'Engage with customers on Tiktok.',
    tradeLetterDate: '2024-08-15',
    distributor: 'CleanHome Supplies',
    promotionDuration: '1 month',
    website: 'https://ecoclean.com/tiktok',
    extractedRemarks: 'Use hashtag #EcoCleanRefresh',
    promotions: [
      { productName: 'Eco-friendly Sponges', barcode: '678901234569', srp: 3.00, discountedPrice: 2.50, discountValue: 0.50, discountPercentage: 16.67 },
    ],
    approvers: ['Frank Miller'],
  },
  {
    id: 'CAM-7Y2U',
    brandName: 'Cozy Knits',
    programName: 'Winter Sweater Sale',
    campaignType: 'Bundle Deals',
    status: 'Active',
    createdBy: 'commercial@demo.com',
    createdAt: '2024-11-01',
    startDate: '2024-11-20',
    endDate: '2024-12-20',
    objectives: 'Clear out winter inventory.',
    tradeLetterDate: '2024-11-01',
    distributor: 'Fashion Direct',
    promotionDuration: '30 days',
    website: 'https://cozyknits.com/sale',
    extractedRemarks: 'All sales final.',
    promotions: [
      { productName: 'Wool Turtleneck', barcode: '890123456789', srp: 80.00, discountedPrice: 50.00, discountValue: 30.00, discountPercentage: 37.5 },
      { productName: 'Cashmere Scarf', barcode: '890123456780', srp: 120.00, discountedPrice: 75.00, discountValue: 45.00, discountPercentage: 37.5 },
    ],
    approvers: ['Ivy Green'],
  }
];

export const mockSrpMasterlist: SKUItem[] = [];
